// // Help Content Data for Each Page
// // This file contains task instructions and API documentation for candidates

// export const helpContent = {
//   login: {
//     pageTitle: 'Login Page',
//     task: 'Integrate the login form with the backend authentication API. Handle successful login by storing user data and redirecting to the dashboard. Display error messages for failed login attempts.',
//     steps: [
//       'Import loginUser function from employeeService',
//       'Call the API with email and password from form state',
//       'Show loading state during API call',
//       'On success: store user data in AuthContext and navigate to /dashboard',
//       'On failure: display error message to user',
//       'Handle validation errors and network errors',
//     ],
//     apis: [
//       {
//         method: 'POST',
//         endpoint: '/api/auth/login',
//         description: 'Authenticate user with email and password',
//         body: {
//           email: 'admin@example.com',
//           password: 'admin123',
//         },
//       },
//     ],
//     notes: [
//       'Use the useAuth hook to access the login function',
//       'Show loading spinner while API request is in progress',
//       'Clear any previous error messages when user starts typing',
//       'Dummy credentials: admin@example.com / admin123',
//     ],
//     expectedBehavior: 'After successful login, user should be redirected to the dashboard page. Token should be stored for subsequent API calls.',
//     serviceFile: 'frontend/src/services/employeeService.js',
//   },

//   dashboard: {
//     pageTitle: 'Dashboard Page',
//     task: 'Display real-time statistics about employees by fetching data from the backend. Calculate and show total employees, active employees, and inactive employees counts.',
//     steps: [
//       'Import getEmployees function from employeeService',
//       'Fetch all employees on component mount',
//       'Calculate statistics from the employee list',
//       'Show loading state while fetching data',
//       'Handle errors gracefully',
//       'Display recent employees list (optional)',
//     ],
//     apis: [
//       {
//         method: 'GET',
//         endpoint: '/api/employees',
//         description: 'Fetch all employees to calculate statistics',
//         queryParams: 'limit, status, sortBy, order',
//       },
//     ],
//     notes: [
//       'You can fetch all employees and calculate stats on frontend',
//       'Or fetch filtered data: ?status=active and ?status=inactive separately',
//       'Show loading skeleton or spinner while data loads',
//       'Handle empty state when no employees exist',
//       'Consider using useEffect for data fetching on mount',
//     ],
//     expectedBehavior: 'Dashboard cards should display accurate counts. Loading state should appear during API call. Error message should show if API fails.',
//     serviceFile: 'frontend/src/services/employeeService.js',
//   },

//   employeeList: {
//     pageTitle: 'Employee List Page',
//     task: 'Implement a fully functional employee list with search, filters, pagination, and CRUD operations. This is the most complex task requiring multiple API integrations.',
//     steps: [
//       'Implement fetchEmployees function to load employee list',
//       'Integrate search functionality (search by name, email, role)',
//       'Add department filter dropdown',
//       'Add status filter (active/inactive)',
//       'Implement pagination controls',
//       'Add delete employee functionality with confirmation',
//       'Add toggle status functionality',
//       'Handle loading, error, and empty states',
//     ],
//     apis: [
//       {
//         method: 'GET',
//         endpoint: '/api/employees',
//         description: 'Fetch employees with filters and pagination',
//         queryParams: 'search, department, status, page, limit, sortBy, order',
//       },
//       {
//         method: 'DELETE',
//         endpoint: '/api/employees/:id',
//         description: 'Delete an employee by ID',
//         params: 'id (employee ID)',
//       },
//       {
//         method: 'PATCH',
//         endpoint: '/api/employees/:id/status',
//         description: 'Toggle employee status (active/inactive)',
//         params: 'id (employee ID)',
//         body: {
//           status: 'active or inactive',
//         },
//       },
//     ],
//     notes: [
//       'Call fetchEmployees whenever search, filter, or page changes',
//       'Use useEffect with dependencies: [search, department, status, currentPage]',
//       'Show confirmation dialog before deleting employee',
//       'Refresh list after delete or status update',
//       'Show "No employees found" when list is empty',
//       'Implement debounce for search input (optional but recommended)',
//       'Handle pagination: disable prev button on page 1, disable next on last page',
//     ],
//     expectedBehavior: 'List should update dynamically based on filters. Search should work across name, email, and role fields. Pagination should show correct page numbers. Delete and status toggle should work instantly.',
//     serviceFile: 'frontend/src/services/employeeService.js',
//   },

//   addEmployee: {
//     pageTitle: 'Add Employee Page',
//     task: 'Create a form to add a new employee to the system. Validate form inputs and handle API responses including duplicate email errors.',
//     steps: [
//       'Import createEmployee function from employeeService',
//       'Collect all form data on submit',
//       'Validate required fields before submitting',
//       'Call createEmployee API with form data',
//       'Show loading state during API call',
//       'Handle validation errors (400) from backend',
//       'Handle duplicate email errors (409)',
//       'On success: show success message and navigate to employee list',
//       'On failure: display error message',
//     ],
//     apis: [
//       {
//         method: 'POST',
//         endpoint: '/api/employees',
//         description: 'Create a new employee',
//         body: {
//           name: 'John Doe',
//           email: 'john@example.com',
//           phone: '+1-555-0100',
//           department: 'Engineering',
//           role: 'Software Engineer',
//           joiningDate: '2024-01-15',
//           salary: 75000,
//           status: 'active',
//           address: '123 Main St, City, State',
//         },
//       },
//     ],
//     notes: [
//       'All fields are required except address (optional)',
//       'Email must be unique (backend will return 409 if duplicate)',
//       'Salary must be a positive number',
//       'Status should be either "active" or "inactive"',
//       'Department options: Engineering, Marketing, HR, Sales, Finance, Operations',
//       'Disable submit button while form is submitting',
//       'Clear form after successful submission (optional)',
//     ],
//     expectedBehavior: 'Form submission should create a new employee and redirect to the employee list. Duplicate email should show specific error message. Validation errors should be displayed near respective fields.',
//     serviceFile: 'frontend/src/services/employeeService.js',
//   },

//   editEmployee: {
//     pageTitle: 'Edit Employee Page',
//     task: 'Load existing employee data, allow user to modify it, and update the employee via API. Handle both fetching and updating operations.',
//     steps: [
//       'Extract employee ID from URL params (useParams hook)',
//       'Import getEmployeeById and updateEmployee from employeeService',
//       'Fetch employee data on component mount',
//       'Pre-fill form with fetched employee data',
//       'Allow user to modify fields',
//       'On submit, call updateEmployee with ID and updated data',
//       'Show loading states for both fetch and update operations',
//       'Handle 404 if employee not found',
//       'Handle duplicate email errors',
//       'On success: show success message and navigate to employee list or details',
//     ],
//     apis: [
//       {
//         method: 'GET',
//         endpoint: '/api/employees/:id',
//         description: 'Fetch employee details by ID',
//         params: 'id (employee ID from URL)',
//       },
//       {
//         method: 'PUT',
//         endpoint: '/api/employees/:id',
//         description: 'Update employee data',
//         params: 'id (employee ID)',
//         body: {
//           name: 'John Doe Updated',
//           email: 'john.updated@example.com',
//           phone: '+1-555-0100',
//           department: 'Engineering',
//           role: 'Senior Software Engineer',
//           joiningDate: '2024-01-15',
//           salary: 85000,
//           status: 'active',
//           address: '123 Main St, City, State',
//         },
//       },
//     ],
//     notes: [
//       'Use useParams to get employee ID from route',
//       'Show loading spinner while fetching employee data',
//       'Show error if employee not found (404)',
//       'Pre-fill all form fields with existing data',
//       'Validate fields before submission (same as add employee)',
//       'Handle duplicate email error (409) if user changes email to existing one',
//       'Disable form while update is in progress',
//     ],
//     expectedBehavior: 'Form should load with existing employee data. Updates should save successfully and redirect to employee list or details. Not found employees should show appropriate error message.',
//     serviceFile: 'frontend/src/services/employeeService.js',
//   },

//   employeeDetails: {
//     pageTitle: 'Employee Details Page',
//     task: 'Display complete information about a single employee. Implement delete and status toggle functionality from this page.',
//     steps: [
//       'Extract employee ID from URL params',
//       'Import getEmployeeById, deleteEmployee, updateEmployeeStatus from employeeService',
//       'Fetch employee data on component mount',
//       'Display all employee information',
//       'Implement delete button with confirmation dialog',
//       'Implement status toggle button',
//       'Show loading state while fetching',
//       'Handle 404 if employee not found',
//       'Navigate to employee list after successful delete',
//     ],
//     apis: [
//       {
//         method: 'GET',
//         endpoint: '/api/employees/:id',
//         description: 'Fetch employee details by ID',
//         params: 'id (employee ID from URL)',
//       },
//       {
//         method: 'DELETE',
//         endpoint: '/api/employees/:id',
//         description: 'Delete employee',
//         params: 'id (employee ID)',
//       },
//       {
//         method: 'PATCH',
//         endpoint: '/api/employees/:id/status',
//         description: 'Update employee status',
//         params: 'id (employee ID)',
//         body: {
//           status: 'active or inactive',
//         },
//       },
//     ],
//     notes: [
//       'Show loading skeleton while employee data loads',
//       'Display all employee fields in a clean card layout',
//       'Show confirmation dialog before delete: "Are you sure you want to delete [Name]?"',
//       'After delete, navigate to /employees page',
//       'Status toggle should update immediately',
//       'Show visual indicator for active vs inactive status',
//       'Handle 404 gracefully with user-friendly message',
//       'Add "Edit" button to navigate to edit page',
//     ],
//     expectedBehavior: 'All employee details should display correctly. Delete should work with confirmation. Status toggle should update the display immediately. 404 should show error message.',
//     serviceFile: 'frontend/src/services/employeeService.js',
//   },
// };
